name: Deploy Django App to DigitalOcean

on:
  push:
    branches:
      - master  # Runs on push to master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/drf-docker-ci-cd:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/drf-docker-ci-cd:latest

      - name: SSH into Droplet and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_DROPLET_IP }}
          username: root
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/drf-docker-ci-cd:latest
            docker stop drf-docker-ci-cd-container || true
            docker rm drf-docker-ci-cd-container || true
            docker run -d --name drf-docker-ci-cd-container -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/drf-docker-ci-cd:latest
